# Generated by Django 2.2.4 on 2019-08-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amoney', models.FloatField(default=100)),
                ('ano', models.CharField(max_length=20)),
                ('apwd', models.CharField(max_length=20)),
                ('atype', models.CharField(default='普通用户', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('bgender', models.NullBooleanField(default=None)),
                ('bage', models.IntegerField(default=18)),
                ('bare', models.CharField(max_length=10)),
                ('bjob', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20)),
                ('gprice', models.FloatField(default=0)),
                ('ginfo', models.TextField(default='暂无内容')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odatetime', models.DateTimeField(auto_now_add=True)),
                ('omoney', models.FloatField(default=0)),
                ('oinfo', models.TextField(default='暂无内容')),
                ('ostatus', models.IntegerField(default=0)),
            ],
        ),
    ]
