# Generated by Django 2.2.4 on 2019-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='gType',
            field=models.CharField(default='未指定', max_length=10),
        ),
    ]
