# Generated by Django 2.2.4 on 2019-08-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_goods_gtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='abuyer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.Buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='gbuyers',
            field=models.ManyToManyField(to='App.Buyer'),
        ),
        migrations.AddField(
            model_name='order',
            name='obuyer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='App.Buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='apwd',
            field=models.CharField(default='111111', max_length=20),
        ),
    ]
