# Generated by Django 2.2.4 on 2019-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='uicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
